server:
  port: 8080
  server-header: "FHIR by alphasingh"
  servlet.context-path: ""

spring:
  data.mongodb.uri: ${MONGO_URI}
  jackson.default-property-inclusion: NON_NULL

logging:
  file: /var/log/cambian/cdr.log
  level.org.mongodb: warn